<html>
<head>
<title>PyException_SetTraceback</title>
<meta name='robots' content='noindex,nofollow'>
<meta name='generator' content='GLOBAL-5.8.1'>
</head>
<body text='#191970' bgcolor='#f5f5dc' vlink='gray'>
<pre>
<a href='../S/2789.html#L146'>PyException_SetTraceback</a>  146 Objects/exceptions.c     if (PyException_SetTraceback(self, tb))
<a href='../S/3091.html#L2973'>PyException_SetTraceback</a> 2973 Python/ceval.c                 PyException_SetTraceback(val, tb);
<a href='../S/3138.html#L1446'>PyException_SetTraceback</a> 1446 Python/pythonrun.c     PyException_SetTraceback(v, tb);
</pre>
</body>
</html>
